language: node_js
node_js: v8.16.1
sudo: required

before_install:
  - npm config set @brightside:registry https://api.bintray.com/npm/ca/brightside
  - npm install -g @brightside/core@lts-incremental
  - zowe --version